leftnav:
- identifier: 87e218ac-cd9e-20c9-12f2-f74132078c23
  name: 'Part 1: Fundamentals of Materials Structure'
  url: /pages/syllabus
  weight: 10
- identifier: external-0ca04b0412ff456b958d8893da4d898b
  name: 'Part 1: Fundamentals of Materials Structure'
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.012S.1x+1T2019/about
  weight: 1000
- identifier: external-f1b1932d0bb846cda0a543202d48255c
  name: 'Part 2: The Crystalline State'
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.012S.2x+1T2019/about
  weight: 1010
- identifier: external-25b705955d48423d863dec89a861a221
  name: 'Part 3: Liquid Crystals, Defects, and Diffusion'
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.012S.3x+1T2019/about
  weight: 1020
